Repository ProvableHQ/snarkOS, pull requests merged in 2021-12, with the labels that each got.

#1385 Add `latest_block_hash` to `getnodestate` RPC endpoint
  src/rpc/rpc.rs
  src/rpc/rpc_impl.rs
Labels: RPC, testnet2

#1392 Testnet2 run* scripts - no restart on push to non-testnet2 branch
  run-client.sh
  run-miner.sh
Labels: testnet2, scripts

#1393 Ensure that storage map operations are not interrupted by a shutdown
  src/network/ledger.rs
  src/network/server.rs
  storage/src/state/ledger.rs
Labels: bug, storage, testnet2

#1404 Bugfix: Ledger Deadlock
  src/network/ledger.rs
  src/network/server.rs
Labels: testnet2

#1397 Don't disconnect from sync nodes too soon
  src/network/peers.rs
Labels: network, testnet2

#1413 fix: ledger not loading the last block when it's just after the batch boundary
  storage/src/state/ledger.rs
Labels: storage, crash, testnet2

#1414 Relax the block spam safeguard
  src/network/peers.rs
Labels: network, performance, testnet2

#1415 Enable more blocking threads
  src/main.rs
Labels: network, performance, testnet2

#1420 Move most of the sending logic from Peers to Peer
  src/network/peers.rs
Labels: network, performance, testnet2

#1425 Make the storage map guard more strict
  storage/src/state/ledger.rs
Labels: storage, testnet2

#1431 Speed up storage validation for block headers
  storage/src/state/ledger.rs
Labels: storage, performance, testnet2

#1433 fix #1432
  src/network/ledger.rs
Labels: performance, testnet2

#1440 Futures 0.3.18 has been Yanked
  Cargo.toml
Labels: dependencies, testnet2

#1448 Remove an allocation from Decoder::decode impl for Message
  src/network/message.rs
Labels: network, performance, testnet2

#1451 feat: disable ansi coloring when stdout being redirected into file
  src/node.rs
Labels: testnet2, logs

#1426 Update dependencies
  Cargo.lock
  Cargo.toml
Labels: dependencies, testnet2

#1435 Shorten DataMap iteration code
  storage/src/storage/rocksdb/iterator.rs
  storage/src/storage/rocksdb/keys.rs
  storage/src/storage/rocksdb/values.rs
Labels: refactor, storage, testnet2

#1441 Fix some clippy lints
  src/network/server.rs
  storage/src/helpers/block_locators.rs
Labels: refactor, testnet2

#1418 Optimize FromBytes for BlockLocators
  storage/src/helpers/block_locators.rs
Labels: sync, performance, testnet2

#1456 Isolate find_maximal_peer from Ledger::update_block_requests
  src/helpers/block_requests.rs
  src/helpers/mod.rs
  src/network/ledger.rs
Labels: refactor, testnet2

#1457 Isolate verify_block_hashes from Ledger::update_block_requests
  src/helpers/block_requests.rs
  src/network/ledger.rs
Labels: refactor, testnet2

#1445 Reduce LedgerState locking, merge 2 collections
  storage/src/state/ledger.rs
Labels: refactor, performance, testnet2

#1459 Refactor Ledger::update_block_requests
  src/network/ledger.rs
Labels: refactor, testnet2

#1461 Refactor Ledger::update_block_requests (2)
  src/helpers/block_requests.rs
  src/network/ledger.rs
Labels: refactor, testnet2

#1396 Stricter task accounting
  src/network/peers.rs
  src/network/server.rs
  src/rpc/rpc.rs
Labels: performance, testnet2

#1477 Don't accept connections when at max peers
  src/network/server.rs
Labels: network, performance, testnet2

#1476 Introduce a MapId object containing the DataMap prefix
  storage/src/state/ledger.rs
  storage/src/state/prover.rs
  storage/src/storage/mod.rs
  storage/src/storage/rocksdb/map.rs
  storage/src/storage/rocksdb/mod.rs
  storage/src/storage/rocksdb/tests.rs
  storage/src/storage/traits.rs
Labels: refactor, storage, testnet2

#1411 Perform ahead-of-time serialization just once when propagating blocks
  src/network/peers.rs
Labels: network, performance, testnet2

#1487 Fix sync node hangs
  src/environment/mod.rs
  src/network/ledger.rs
Labels: sync, network, testnet2

#1482 Drop the block requests lock before disconnecting
  src/network/ledger.rs
Labels: network, testnet2

#1483 fix windows build
  Cargo.lock
  Cargo.toml
Labels: dependencies, testnet2, windows

#1436 Speed up CircularMap
  src/helpers/circular_map.rs
  src/network/ledger.rs
Labels: performance, testnet2

#1490 Tweak sync node threading
  src/main.rs
Labels: performance, testnet2
