Repository ProvableHQ/snarkOS, pull requests merged in 2021-10, with the labels that each got.

#1182 A more thorough storage trim
  network/src/peers/peers.rs
  storage/src/digest.rs
  storage/src/storage/async_adapter.rs
  storage/src/storage/key_value/store.rs
  storage/src/storage/sqlite/sync.rs
  storage/src/storage/storage.rs
  storage/src/storage/sync.rs
  storage/src/trim.rs
Labels: storage, performance

#1190 Connection metrics tests
  .circleci/config.yml
  Cargo.lock
  metrics/Cargo.toml
  metrics/src/lib.rs
  metrics/src/metric_types.rs
  metrics/src/snapshots.rs
  metrics/src/stats.rs
  testing/Cargo.toml
  testing/src/lib.rs
  testing/src/metrics/mod.rs
Labels: metrics, tests

#1192 Blocked syncing
  consensus/src/consensus/inner/agent.rs
  consensus/src/consensus/mod.rs
  consensus/src/ledger/merkle.rs
  network/src/node.rs
  network/src/sync/blocks/interface.rs
  snarkos/init.rs
  testing/src/network/sync.rs
  testing/src/sync/mod.rs
Labels: sync, performance

#1196 Check if min-peers is not greater than max-peers
  snarkos/config.rs
Labels: ergonomics

#1198 Non-blocking block serialization
  network/src/errors/network.rs
  network/src/sync/blocks/interface.rs
Labels: performance

#1194 Update dependencies
  Cargo.lock
  Cargo.toml
  network/src/peers/peers.rs
  storage/Cargo.toml
Labels: dependencies

#1200 Internal state check for block state
  Cargo.lock
  consensus/src/consensus/inner/agent.rs
  consensus/src/consensus/inner/commit.rs
  consensus/src/consensus/mod.rs
  storage/Cargo.toml
  storage/src/storage/async_adapter.rs
  storage/src/storage/sqlite/sync.rs
Labels: ergonomics
