Repository ProvableHQ/snarkOS, pull requests merged in 2021-11, with the labels that each got.

#1288 Docker builds
  .circleci/config.yml
  Dockerfile
  start
Labels: configurations

#1295 Mine blocks in the context of a blocking task
  src/network/ledger.rs
Labels: performance, mining

#1313 Fix the snarkos-testing setup, start logging earlier
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/node.rs
Labels: dependencies, tests

#1319 Use more fine-grained locks in Peers
  src/network/peers.rs
  src/rpc/rpc_impl.rs
Labels: performance

#1315 Check if Server frees its resources on shutdown
  src/network/server.rs
  testing/src/client_node.rs
  testing/tests/network/cleanups.rs
Labels: tests

#1318 Use more fine-grained locks for Ledger and Peers
  ledger/src/state/ledger.rs
  ledger/src/state/tests.rs
  src/helpers/circular_map.rs
  src/network/ledger.rs
  src/network/peers.rs
  src/network/server.rs
  src/rpc/rpc.rs
  src/rpc/rpc_impl.rs
Labels: performance

#1326 Reduce blocking when (de)serializing messages
  .circleci/config.yml
  src/main.rs
  src/network/ledger.rs
  src/network/message.rs
  src/network/peers.rs
  testing/src/test_node.rs
  testing/tests/common/mod.rs
Labels: performance

#1331 Avoid the write()s in Ledger::initialize_peer
  src/network/ledger.rs
Labels: performance

#1334 Introduce a BlockRequest object to speed up block request queries
  src/network/ledger.rs
Labels: performance

#1332 Reduce the scope of the block request locks
  src/network/ledger.rs
Labels: performance

#1335 Optimize lock access and reduce the number of queries in Ledger::update_block_requests
  src/network/ledger.rs
Labels: performance

#1337 Reduce the scope of the unconfirmed blocks write lock in update_ledger
  src/network/ledger.rs
Labels: performance

#1339 Display tracing logs when running with --display
  src/display/display.rs
  src/display/logs.rs
  src/main.rs
  src/node.rs
Labels: feature
