Repository ProvableHQ/snarkOS, pull requests merged in 2021-06, with the labels that each got.

#797 Introduce a block storage validator tool
  Cargo.lock
  storage/Cargo.toml
  storage/src/lib.rs
  storage/src/validator.rs
Labels: feature, storage, tests

#804 Increase the default peer counts
  snarkos/config.rs
Labels: network, performance

#815 Update metrics-related crates
  Cargo.lock
  Cargo.toml
  network/Cargo.toml
  network/src/stats.rs
  rpc/Cargo.toml
Labels: dependencies

#816 Improve test data
  benchmarks/syncing/syncing.rs
  testing/examples/test_blocks.rs
  testing/scripts/generate_test_data.sh
  testing/src/network/blocks.rs
  testing/src/network/mod.rs
  testing/src/network/sync.rs
  testing/src/sync/data.rs
  testing/src/sync/mod.rs
  testing/src/sync/test_blocks_100
  testing/src/sync/test_blocks_100_2
Labels: tests

#821 Spawn the prometheus exporter within the main async runtime
  Cargo.lock
  Cargo.toml
  network/Cargo.toml
  network/src/node.rs
  snarkos/main.rs
Labels: design, metrics

#781 Don't omit the first 2 operations in decommit_latest_block
  consensus/tests/consensus_sidechain.rs
  storage/src/ledger.rs
  storage/src/objects/block.rs
  storage/src/objects/block_path.rs
  storage/src/objects/dpc_state.rs
Labels: storage

#848 Fix the version of metrics-exporter-prometheus
  Cargo.lock
  network/Cargo.toml
Labels: dependencies

#855 Revert the removal of the check for duplicate blocks
  storage/src/objects/block_path.rs
Labels: performance, sync

#858 Improve the block storage validator, add 2 fork+sync tests
  Cargo.lock
  benchmarks/syncing/syncing.rs
  consensus/Cargo.toml
  consensus/tests/consensus_sidechain.rs
  storage/src/validator.rs
  testing/src/network/sync.rs
  testing/src/sync/data.rs
  testing/src/sync/test_blocks_100_1
Labels: sync, tests

#857 Update snarkVM and other deps
  Cargo.lock
  Cargo.toml
  benchmarks/Cargo.toml
  consensus/Cargo.toml
  metrics/Cargo.toml
  network/Cargo.toml
  parameters/Cargo.toml
  rpc/Cargo.toml
  storage/Cargo.toml
  testing/Cargo.toml
  toolkit/Cargo.toml
Labels: dependencies

#864 Add a transaction storage verifier + fixer
  Cargo.lock
  consensus/tests/consensus_sidechain.rs
  storage/Cargo.toml
  storage/src/validator.rs
Labels: feature, storage, sync

#868 Remove nightly CI, temporarily remove broken external doc macros
  .circleci/config.yml
  .github/workflows/ci.yml
  .rusty-hook.toml
  Cargo.lock
  Cargo.toml
  build.rs
  network/Cargo.toml
  network/build.rs
  network/src/lib.rs
  network/src/message/message.rs
  network/src/message/version.rs
  rpc/Cargo.toml
  rpc/build.rs
  rpc/src/lib.rs
  rpc/src/rpc_trait.rs
Labels: configurations

#871 Fix syncing which involves previously known blocks
  consensus/src/consensus.rs
  consensus/tests/consensus_sidechain.rs
  network/src/sync/master.rs
  storage/src/objects/block.rs
  storage/src/objects/block_path.rs
Labels: performance, sync

#867 Update JSON-RPC docs
  rpc/documentation/private_endpoints/createaccount.md
  rpc/documentation/public_endpoints/decoderawtransaction.md
  rpc/documentation/public_endpoints/getblock.md
  rpc/documentation/public_endpoints/gettransactioninfo.md
Labels: documentation

#875 A range of tweaks and fixes around storage and its verifier
  benchmarks/syncing/syncing.rs
  consensus/tests/consensus_sidechain.rs
  rpc/src/rpc_impl.rs
  storage/src/objects/insert_commit.rs
  storage/src/objects/transaction.rs
  storage/src/validator.rs
  testing/src/network/sync.rs
  testing/src/storage/mod.rs
  testing/src/sync/data.rs
Labels: RPC, storage

#881 A range of clippy fixes
  consensus/src/consensus.rs
  consensus/src/memory_pool.rs
  network/src/message/serialization.rs
  network/src/peers/peer/handshake.rs
  network/src/peers/peer/network.rs
  network/src/peers/peers.rs
  network/src/sync/master.rs
  network/src/sync/memory_pool.rs
  rpc/src/rpc_impl.rs
  rpc/src/rpc_impl_protected.rs
  storage/src/key_value.rs
  storage/src/ledger.rs
  storage/src/objects/insert_commit.rs
  storage/src/objects/ledger_scheme.rs
  storage/src/objects/records.rs
  storage/src/objects/transaction.rs
  storage/src/validator.rs
  toolkit/src/dpc/transaction_kernel_builder.rs
  toolkit/src/record/record.rs
Labels: refactor

#880 Longer RPC error responses
  rpc/src/custom_rpc_server.rs
Labels: RPC
