Repository ProvableHQ/snarkOS, pull requests merged in 2021-09, with the labels that each got.

#1115 Non-blocking Merkle tree rebuilds
  .circleci/config.yml
  consensus/src/consensus/inner/commit.rs
  consensus/src/ledger/dummy.rs
  consensus/src/ledger/merkle.rs
  consensus/src/ledger/mod.rs
  consensus/tests/consensus_dpc.rs
  rpc/tests/rpc_tests.rs
Labels: performance

#1118 Expand the scope of a blocking task
  network/src/sync/blocks.rs
Labels: performance

#1099 Move the crawler to its own binary
  Cargo.toml
  benchmarks/network/syncing.rs
  bin/crawler.rs
  bin/snarkos.rs
  network/src/inbound/inbound.rs
  network/src/node.rs
  network/src/peers/peers.rs
  network/src/sync/blocks.rs
  network/src/sync/master.rs
  network/src/sync/memory_pool.rs
  network/src/sync/miner.rs
  network/tests/cleanup.rs
  network/tests/fuzzing.rs
  network/tests/handshake.rs
  network/tests/peers.rs
  network/tests/topology.rs
  rpc/src/custom_rpc_server.rs
  rpc/src/error.rs
  rpc/src/rpc_impl.rs
  rpc/src/rpc_impl_protected.rs
  rpc/tests/protected_rpc_tests.rs
  rpc/tests/rpc_tests.rs
  snarkos/config.rs
  snarkos/display.rs
  testing/src/network/mod.rs
  testing/src/network/sync.rs
  testing/src/network/topology.rs
Labels: refactor

#1123 Improve the RPC tests
  rpc/tests/rpc_tests.rs
Labels: tests, RPC

#1122 Upgrade the miner termination log from TRACE to DEBUG
  consensus/src/miner.rs
Labels: ergonomics

#1125 Some workspace maintenance
  Cargo.lock
  Cargo.toml
  consensus/Cargo.toml
  network/Cargo.toml
  network/src/peers/peer/connector.rs
  network/src/peers/peer/outbound_handler.rs
  network/src/peers/peer/peer_events.rs
  network/src/peers/peer/receiver.rs
  network/src/peers/peer_book.rs
  parameters/Cargo.toml
  rpc/Cargo.toml
  rpc/src/rpc_impl.rs
  storage/Cargo.toml
  storage/src/storage/mod.rs
Labels: dependencies

#1124 Move some MemoryPool methods over to ConsensusInner
  consensus/src/consensus/inner/commit.rs
  consensus/src/consensus/inner/mod.rs
  consensus/src/consensus/inner/transaction.rs
  consensus/src/memory_pool.rs
Labels: refactor

#1126 Report potential canon tip via the `getnetworkgraph` rpc
  network/src/topology.rs
  rpc/documentation/public_endpoints/getnetworkgraph.md
  rpc/src/rpc_impl.rs
  rpc/src/rpc_types.rs
Labels: feature

#1127 Spawn a blocking task for transaction verification
  consensus/src/consensus/inner/agent.rs
  consensus/src/consensus/inner/commit.rs
  consensus/src/consensus/inner/transaction.rs
  consensus/src/ledger/mod.rs
  rpc/tests/rpc_tests.rs
Labels: performance

#1119 Non-blocking header verification
  Cargo.lock
  Cargo.toml
  bin/snarkos.rs
  consensus/src/consensus/inner/commit.rs
Labels: performance

#1131 Add a block processing benchmark
  Cargo.lock
  benchmarks/Cargo.toml
  benchmarks/network/block_processing.rs
  benchmarks/network/syncing.rs
  bin/crawler.rs
  bin/snarkos.rs
  consensus/Cargo.toml
  consensus/src/consensus/inner/agent.rs
  consensus/src/consensus/message.rs
  consensus/src/consensus/mod.rs
  network/src/config.rs
  network/src/node.rs
  network/tests/topology.rs
  rpc/tests/protected_rpc_tests.rs
  rpc/tests/rpc_tests.rs
  storage/src/storage/async_adapter.rs
  storage/src/storage/key_value/store.rs
  storage/src/storage/sqlite/sync.rs
  storage/src/storage/storage.rs
  storage/src/storage/sync.rs
  testing/Cargo.toml
  testing/src/network/mod.rs
Labels: tests, performance

#1138 Replace futures::select with tokio::select
  network/src/peers/peer/peer.rs
  network/src/peers/peer_book.rs
  network/src/sync/blocks/base.rs
Labels: refactor

#1082 replace base image with Ubuntu 18.04 and Rust stable
  Dockerfile
  README.md
  docker-compose.yml
Labels: configurations

#1172 Make the getnodeinfo RPC work for non-client nodes
  rpc/src/rpc_impl.rs
Labels: RPC

#1174 Make the getnetworkgraph RPC not return nodes with height 0 as potential forks
  network/src/topology.rs
Labels: RPC

#1175 Fix the connected count metric
  network/src/peers/peer/receiver.rs
Labels: metrics, RPC

#1180 Remove the sqlite cli flag
  snarkos/config.rs
  snarkos/parameters/flag.rs
Labels: ergonomics

#1179 Re-structure block metrics
  consensus/src/consensus/inner/commit.rs
  consensus/src/consensus/inner/mod.rs
  metrics/grafana/dashboard.json
  metrics/src/names.rs
  metrics/src/snapshots.rs
  metrics/src/stats.rs
  network/src/node.rs
  network/src/peers/peer/inbound_handler.rs
  network/src/sync/blocks/interface.rs
  network/src/sync/miner.rs
  rpc/documentation/public_endpoints/getnodestats.md
Labels: refactor, metrics

#1185 Don't increment the related metric if try_send fails
  metrics/src/wrapped_mpsc.rs
Labels: metrics
