Repository ProvableHQ/snarkOS, pull requests merged in 2022-05, with the labels that each got.

#1712 Add fuzz tests for the network message decoder
  fuzz/.gitignore
  fuzz/Cargo.toml
  fuzz/fuzz_targets/deserialization.rs
  fuzz/fuzz_targets/network.rs
Labels: tests

#1722 Update jsonrpsee to 0.11
  .crawler/Cargo.toml
  .integration/Cargo.toml
  .synthetic_node/Cargo.toml
  Cargo.lock
  Cargo.toml
  rpc/Cargo.toml
  rpc/src/context.rs
  rpc/src/tests.rs
Labels: dependencies

#1723 Remove port comparison in connection limit checks
  network/src/peers.rs
Labels: network

#1752 Update dependencies
  .crawler/Cargo.toml
  Cargo.lock
Labels: dependencies

#1754 Update pea2pea to 0.37, run cargo update
  .crawler/Cargo.toml
  .crawler/src/constants.rs
  .crawler/src/crawler.rs
  .integration/Cargo.toml
  .synthetic_node/Cargo.toml
  .synthetic_node/src/lib.rs
  Cargo.lock
Labels: dependencies

#1708 A few test tweaks
  .integration/Cargo.toml
  .integration/src/client_node.rs
  .integration/src/test_node.rs
  .integration/tests/network/basic_connectivity.rs
  .integration/tests/network/perf.rs
  Cargo.lock
  Cargo.toml
  environment/src/lib.rs
  network/src/ledger.rs
  rpc/src/tests.rs
  snarkos/server.rs
  storage/Cargo.toml
  storage/benches/blocks_3
  storage/src/state/ledger.rs
  storage/src/state/tests.rs
Labels: tests

#1719 Feat: round trip time metrics for request/response cycles
  .crawler/src/crawler.rs
  .integration/src/test_node.rs
  environment/src/network/message.rs
  metrics/grafana/dashboard.json
  metrics/src/lib.rs
  metrics/src/names.rs
  network/src/ledger.rs
  network/src/peer.rs
  network/src/peers.rs
Labels: feature, metrics

#1775 Run cargo update
  Cargo.lock
Labels: dependencies

#1777 Update dependencies
  Cargo.lock
  Cargo.toml
Labels: dependencies

#1726 Disable some resource logs
  environment/src/helpers/resources.rs
Labels: logs

#1727 Introduce an object with combined state
  .crawler/src/crawler.rs
  .crawler/src/known_network.rs
  .crawler/src/metrics.rs
  .crawler/src/storage.rs
  .integration/src/client_node.rs
  .integration/src/test_node.rs
  .integration/tests/network/perf.rs
  .synthetic_node/src/lib.rs
  Cargo.lock
  environment/src/helpers/mod.rs
  environment/src/helpers/status.rs
  environment/src/lib.rs
  environment/src/network/message.rs
  network/Cargo.toml
  network/src/ledger.rs
  network/src/lib.rs
  network/src/operator.rs
  network/src/peer.rs
  network/src/peers.rs
  network/src/prover.rs
  network/src/state.rs
  rpc/src/context.rs
  rpc/src/rpc_impl.rs
  rpc/src/tests.rs
  snarkos/server.rs
Labels: refactor

#1757 Add a block dump utility test
  Cargo.lock
  storage/Cargo.toml
  storage/src/state/ledger.rs
  storage/tests/dump_blocks.rs
Labels: feature, tests

#1776 Fix new clippy lints
  snarkos/display/aleo.rs
  snarkos/node.rs
  snarkos/updater.rs
Labels: refactor

#1764 Feat: inbound message count metrics
  metrics/grafana/dashboard.json
  metrics/src/lib.rs
  metrics/src/names.rs
  network/src/peer.rs
Labels: feature, metrics

#1768 Add a ciphertext_lookup_by_commitment benchmark
  storage/benches/lookups.rs
Labels: tests

#1769 Add an informational ledger breakdown test
  storage/src/storage/rocksdb/map.rs
  storage/src/storage/rocksdb/mod.rs
  storage/tests/ledger_breakdown.rs
Labels: tests
