Repository ProvableHQ/snarkOS, pull requests merged in 2022-06, with the labels that each got.

#1786 Update dependencies
  Cargo.lock
  Cargo.toml
  metrics/Cargo.toml
  metrics/src/utils.rs
  storage/Cargo.toml
Labels: dependencies

#1792 Clippy lints
  snarkos/node.rs
  storage/src/state/ledger.rs
  storage/src/state/operator.rs
  storage/src/state/prover.rs
Labels: ergonomics

#1731 Safer storage traits
  network/src/helpers/block_requests.rs
  network/src/ledger.rs
  network/src/operator.rs
  network/src/prover.rs
  rpc/src/tests.rs
  snarkos/node.rs
  snarkos/server.rs
  storage/benches/insertion.rs
  storage/benches/lookups.rs
  storage/benches/opening.rs
  storage/src/state/ledger.rs
  storage/src/state/operator.rs
  storage/src/state/prover.rs
  storage/src/state/tests.rs
  storage/src/storage/mod.rs
  storage/src/storage/rocksdb/map.rs
  storage/src/storage/rocksdb/mod.rs
  storage/src/storage/rocksdb/tests.rs
  storage/src/storage/traits.rs
  storage/tests/dump_blocks.rs
  storage/tests/ledger_breakdown.rs
  storage/tests/ledger_validation.rs
Labels: refactor, storage

#1809 Update deps
  .crawler/Cargo.toml
  .crawler/src/crawler.rs
  .integration/Cargo.toml
  .integration/src/test_node.rs
  .synthetic_node/Cargo.toml
  .synthetic_node/src/lib.rs
  Cargo.lock
Labels: dependencies

#1807 Add a simple license checker
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  build.rs
Labels: feature

#1817 Update dependencies
  Cargo.lock
Labels: dependencies
