Repository ProvableHQ/snarkOS, pull requests merged in 2022-01, with the labels that each got.

#1427 Introduces pool functionality to network protocol
  Cargo.lock
  Cargo.toml
  README.md
  src/environment/mod.rs
  src/network/ledger.rs
  src/network/message.rs
  src/network/mod.rs
  src/network/operator.rs
  src/network/peers.rs
  src/network/prover.rs
  src/network/server.rs
  src/node.rs
  src/rpc/rpc.rs
  storage/Cargo.toml
  storage/src/helpers/block_locators.rs
  storage/src/lib.rs
  storage/src/state/ledger.rs
  storage/src/state/mod.rs
  storage/src/state/operator.rs
  storage/src/storage/rocksdb/map.rs
  testing/Cargo.toml
  testing/src/client_node.rs
Labels: feature, mining, testnet2

#1527 Updates `PoolResponse` from block header to PoSW proof
  Cargo.lock
  Cargo.toml
  src/environment/mod.rs
  src/helpers/block_requests.rs
  src/network/message.rs
  src/network/operator.rs
  src/network/peer.rs
  src/network/peers.rs
  src/network/prover.rs
  storage/Cargo.toml
  testing/Cargo.toml
Labels: bug

#1531 Attempts a reconnect from prover to operator periodically
  src/network/server.rs
Labels: bug

#1529 Refactors `BlockRequest` and adds tests for it
  src/helpers/block_request.rs
  src/helpers/mod.rs
  src/network/ledger.rs
Labels: refactor, testnet2

#1530 Unifies the thread pool for the node
  src/environment/mod.rs
  src/network/operator.rs
  src/network/prover.rs
Labels: refactor, testnet2

#1543 Deps: run `cargo update`
  Cargo.lock
Labels: dependencies, testnet2

#1447 Speed up network message serialization & propagation
  src/network/message.rs
  testing/src/test_node.rs
Labels: network, performance, testnet2

#1539 Fix/rpc request serde
  Cargo.toml
  src/rpc/rpc.rs
Labels: RPC, testnet2

#1532 Move the block locator length check, deduplicate some logic in update_peer
  src/network/ledger.rs
  storage/src/helpers/block_locators.rs
  storage/src/state/ledger.rs
Labels: refactor, performance, testnet2

#1545 Add CI for `storage` and `testing` modules
  .circleci/config.yml
  storage/src/state/ledger.rs
  testing/tests/network/basic_connectivity.rs
Labels: configurations, tests, testnet2

#1549 Expose `cuda` feature flag
  Cargo.lock
  Cargo.toml
  src/rpc/rpc_impl.rs
  storage/Cargo.toml
  storage/src/state/ledger.rs
  storage/src/state/tests.rs
  testing/Cargo.toml
Labels: feature, performance, testnet2

#1565 Update dependencies
  Cargo.lock
Labels: dependencies, testnet2

#1552 Introduce storage lookup benchmarks
  Cargo.lock
  storage/Cargo.toml
  storage/benches/blocks_100
  storage/benches/blocks_1000
  storage/benches/lookups.rs
  storage/src/state/ledger.rs
Labels: storage, tests, performance, testnet2

#1566 Only enable snappy feature of rocksdb
  storage/Cargo.toml
Labels: storage, testnet2

#1480 Feat: Prometheus exporter
  Cargo.lock
  Cargo.toml
  metrics/Cargo.toml
  metrics/src/lib.rs
  src/network/server.rs
Labels: feature, metrics, testnet2

#1570 Feat: deferred de/serialisation for transactions
  src/network/message.rs
  src/network/peer.rs
  src/network/prover.rs
Labels: network, performance, testnet2

#1589 Fix lints from the updated nightly
  src/network/ledger.rs
  src/rpc/rpc.rs
  storage/benches/lookups.rs
  storage/src/state/tests.rs
Labels: refactor, testnet2

#1577 Make message deserialisation generic over `Read`
  src/network/message.rs
  testing/src/test_node.rs
Labels: network, performance, crash, testnet2

#1572 Add more storage benches
  storage/Cargo.toml
  storage/benches/insertion.rs
  storage/benches/lookups.rs
  storage/benches/opening.rs
Labels: tests, testnet2

#1571 Update dependencies
  Cargo.lock
  Cargo.toml
  metrics/Cargo.toml
  metrics/src/lib.rs
  src/display/overview.rs
  testing/Cargo.toml
  testing/src/test_node.rs
  testing/tests/common/mod.rs
  testing/tests/network/manual_testing.rs
Labels: dependencies, testnet2
