Repository ProvableHQ/snarkOS, pull requests merged in 2022-02, with the labels that each got.

#1600 Replace `chrono` with `time` (RUSTSEC-2020-0159)
  Cargo.lock
  Cargo.toml
  src/network/ledger.rs
  src/rpc/rpc_impl.rs
  storage/Cargo.toml
  storage/src/state/ledger.rs
Labels: dependencies, security

#1625 Change the CircleCI resource class from 2xlarge to xlarge
  .circleci/config.yml
Labels: configurations

#1623 Fix the Discord links
  README.md
  src/display/aleo.rs
Labels: documentation

#1618 Return shares for prover regardless of canon block status
  storage/src/state/operator.rs
Labels: bug

#1624 Provide peers with the reason for disconnecting from them
  src/helpers/block_requests.rs
  src/network/ledger.rs
  src/network/message.rs
  src/network/peer.rs
  src/network/peers.rs
  testing/src/test_node.rs
Labels: feature, network, testnet2

#1573 Don't deserialize values in DataMap::contains_key
  storage/src/storage/rocksdb/map.rs
Labels: storage, performance, testnet2

#1630 Fix handshake disconnect
  src/network/peer.rs
Labels: network, testnet2

#1614 Update dependencies
  Cargo.lock
  Cargo.toml
  storage/Cargo.toml
  testing/Cargo.toml
  testing/src/test_node.rs
Labels: dependencies

#1635 Log received RPC requests
  src/rpc/context.rs
Labels: feature, RPC, logs
