Repository ProvableHQ/snarkOS, pull requests merged in 2022-03, with the labels that each got.

#1657 Use an alias for the current network
  .integration/src/client_node.rs
  .integration/src/test_node.rs
  environment/src/lib.rs
  network/src/helpers/block_request.rs
  network/src/helpers/block_requests.rs
  rpc/src/tests.rs
  snarkos/lib.rs
  snarkos/node.rs
  storage/benches/insertion.rs
  storage/benches/lookups.rs
  storage/benches/opening.rs
  storage/src/helpers/block_locators.rs
  storage/src/state/tests.rs
  storage/tests/ledger_validation.rs
Labels: refactor

#1663 Squash a few perf TODOs
  network/src/peers.rs
  storage/src/state/ledger.rs
Labels: refactor, performance

#1664 Introduce a notion of trusted peers
  environment/src/lib.rs
  network/src/peers.rs
Labels: feature, network

#1656 Allow miner stats to be retrieved while the node is running
  network/src/prover.rs
  snarkos/node.rs
  storage/src/state/prover.rs
Labels: crash, mining

#1652 More comprehensive resource management
  Cargo.lock
  environment/Cargo.toml
  environment/src/helpers/resources.rs
  network/src/ledger.rs
  network/src/operator.rs
  network/src/peer.rs
  network/src/peers.rs
  network/src/prover.rs
  rpc/src/tests.rs
  snarkos/node.rs
  snarkos/server.rs
Labels: feature

#1653 Introduce feature-gated task metrics
  Cargo.lock
  Cargo.toml
  environment/Cargo.toml
  environment/src/helpers/resources.rs
Labels: feature, metrics

#1669 Bump dependencies
  .crawler/Cargo.toml
  .integration/Cargo.toml
  .synthetic_node/Cargo.toml
  Cargo.lock
Labels: dependencies

#1668 Improve the crawler, add a related test
  .crawler/Cargo.toml
  .crawler/src/connection.rs
  .crawler/src/constants.rs
  .crawler/src/crawler.rs
  .crawler/src/known_network.rs
  .crawler/tests/peering.rs
  .integration/src/lib.rs
  .integration/tests/common/mod.rs
  .integration/tests/metrics/mod.rs
  .integration/tests/network/basic_connectivity.rs
  .integration/tests/network/cleanups.rs
  .synthetic_node/src/lib.rs
  Cargo.lock
Labels: feature, tests, performance

#1672 Further improvements to the network crawler
  .crawler/src/constants.rs
  .crawler/src/crawler.rs
  .crawler/src/known_network.rs
  .crawler/src/main.rs
  .crawler/tests/peering.rs
  .integration/src/test_node.rs
  .integration/tests/network/basic_connectivity.rs
  .synthetic_node/Cargo.toml
  .synthetic_node/src/lib.rs
  Cargo.lock
  environment/src/helpers/node_type.rs
  environment/src/helpers/status.rs
Labels: network, performance

#1674 Finishing touches for the network crawler
  .crawler/src/connection.rs
  .crawler/src/crawler.rs
  .crawler/src/known_network.rs
  .crawler/tests/peering.rs
  .synthetic_node/src/lib.rs
Labels: feature

#1676 Add a short sleep to a flaky test
  .integration/tests/network/basic_connectivity.rs
Labels: tests

#1682 Add feature-gated persistent storage to the network crawler
  .crawler/Cargo.toml
  .crawler/src/constants.rs
  .crawler/src/crawler.rs
  .crawler/src/known_network.rs
  .crawler/src/lib.rs
  .crawler/src/main.rs
  .crawler/src/storage.rs
  .crawler/tests/peering.rs
  Cargo.lock
Labels: feature, network

#1684 Metric dependency updates
  Cargo.lock
  metrics/Cargo.toml
  metrics/src/lib.rs
  metrics/src/utils.rs
Labels: dependencies

#1685 Fix prometheus feature compilation
  snarkos/server.rs
Labels: bug, metrics, compilation

#1687 Include more network metrics in the crawler, store connections
  .crawler/Cargo.toml
  .crawler/src/constants.rs
  .crawler/src/crawler.rs
  .crawler/src/known_network.rs
  .crawler/src/lib.rs
  .crawler/src/metrics.rs
  .crawler/src/storage.rs
  Cargo.lock
Labels: feature, network

#1677 Move from structopt to clap
  .crawler/Cargo.toml
  .crawler/src/crawler.rs
  .crawler/src/main.rs
  .crawler/tests/peering.rs
  .integration/Cargo.toml
  .integration/src/client_node.rs
  Cargo.lock
  Cargo.toml
  snarkos/main.rs
  snarkos/node.rs
Labels: dependencies

#1694 Restructure crawler args, introduce a new storage table
  .crawler/src/crawler.rs
  .crawler/src/storage.rs
Labels: crawler

#1695 A few fixes and tweaks for the network crawler
  .crawler/src/constants.rs
  .crawler/src/crawler.rs
  .crawler/src/metrics.rs
  .synthetic_node/src/lib.rs
Labels: crawler

#1688 Proposal: move some objects to snarkos-environment
  .circleci/config.yml
  .crawler/Cargo.toml
  .crawler/src/crawler.rs
  .integration/Cargo.toml
  .integration/src/lib.rs
  .integration/src/test_node.rs
  .integration/tests/tests.rs
  .synthetic_node/Cargo.toml
  .synthetic_node/src/lib.rs
  Cargo.lock
  environment/Cargo.toml
  environment/src/helpers/block_locators.rs
  environment/src/helpers/mod.rs
  environment/src/lib.rs
  environment/src/network/message.rs
  environment/src/network/mod.rs
  network/Cargo.toml
  network/src/helpers/block_requests.rs
  network/src/ledger.rs
  network/src/lib.rs
  network/src/operator.rs
  network/src/peer.rs
  network/src/peers.rs
  network/src/prover.rs
  rpc/Cargo.toml
  rpc/src/rpc_impl.rs
  storage/Cargo.toml
  storage/src/lib.rs
  storage/src/state/ledger.rs
  storage/src/state/mod.rs
Labels: configurations, dependencies

#1690 Allow multiple addresses when using --connect
  snarkos/node.rs
Labels: feature, network

#1699 Restore missing CI integration tests
  .circleci/config.yml
Labels: configurations, tests

#1689 Take care of some clippy lints
  .integration/src/test_node.rs
  .integration/tests/metrics/mod.rs
  metrics/src/lib.rs
  metrics/src/utils.rs
Labels: refactor

#1707 Run cargo update
  Cargo.lock
Labels: dependencies

#1692 Tweaks to the node's cleanups
  .integration/src/client_node.rs
  .integration/tests/network/cleanups.rs
  environment/src/helpers/resources.rs
  network/src/peer.rs
  network/src/peers.rs
Labels: refactor, tests, logs
