Repository ProvableHQ/snarkOS, pull requests merged in 2024-05, with the labels that each got.

#3276 [hotfix] Update the genesis targets for TestnetV0
  Cargo.toml
Labels: hotfix

#3277 [hotfix] [bump] snarkVM mainnet rev fddd8b9 - testnetv0-genesis-target
  Cargo.toml
Labels: hotfix

#3275 Avoid unnecessary calculations in propose_batch
  node/bft/src/primary.rs
Labels: performance

#3283 Updated canary genesis block - bump snarkVM rev - 9c3bd7f
  Cargo.toml
Labels: bug
