Repository ProvableHQ/snarkOS, pull requests merged in 2024-11, with the labels that each got.

#3358 Limit parallel processing for clients
  Cargo.lock
  node/Cargo.toml
  node/src/client/mod.rs
  node/src/client/router.rs
Labels: enhancement, v1.1.4

#3435 Remove test feature from cfg
  node/bft/src/gateway.rs
  node/router/src/handshake.rs
  node/router/src/lib.rs
Labels: bug, v1.1.4

#3436 Canary release week 24.46 - v1.1.4
  Cargo.lock
  Cargo.toml
  node/rest/Cargo.toml
Labels: release

#3445 Canary release week 24.47 - v1.2.1
  Cargo.lock
  Cargo.toml
  node/rest/Cargo.toml
Labels: release, v1.2.1

#3446 [hotfix] Canary release week 24.47 - v1.2.2
  Cargo.lock
  Cargo.toml
  node/rest/Cargo.toml
Labels: hotfix, release
