Repository ProvableHQ/snarkOS, pull requests merged in 2024-06, with the labels that each got.

#3308 Update CircleCI resource classes
  .circleci/config.yml
Labels: enhancement

#3309 Fix tests
  Cargo.lock
  Cargo.toml
  cli/src/commands/start.rs
Labels: release

#3318 fix(tcp): fix outbound tcp requests not respecting --node bind port
  node/tcp/src/tcp.rs
Labels: bug

#3323 Fix header image, links, build instructions, rightsize CI
  .circleci/config.yml
  README.md
Labels: enhancement

#3325 Canary v0.3.0 release
  Cargo.toml
Labels: release

#3333 Testnet Beta v0.3.0 release
  Cargo.toml
Labels: release
