Repository ProvableHQ/snarkOS, pull requests merged in 2025-03, with the labels that each got.

#3517 [Release] Mainnet v3.3.2
  .integration/Cargo.toml
  .resources/release-version
  Cargo.lock
  Cargo.toml
  account/Cargo.toml
  cli/Cargo.toml
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/storage-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/tcp/Cargo.toml
Labels: release

#3504 Prioritize removing clients over validators in the heartbeat logic
  node/router/src/heartbeat.rs
  node/router/src/helpers/cache.rs
  node/router/src/lib.rs
  node/router/tests/heartbeat.rs
  node/sync/src/block_sync.rs
Labels: v3.5.0

#3489 [Feature] Introduce `cuda` feature flag
  Cargo.lock
  Cargo.toml
  README.md
  account/Cargo.toml
  cli/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/sync/Cargo.toml
  run-prover.sh
Labels: v3.5.0

#3547 [Release] Mainnet 3.4.0
  .circleci/config.yml
  .integration/Cargo.toml
  .resources/release-version
  Cargo.lock
  Cargo.toml
  account/Cargo.toml
  cli/Cargo.toml
  cli/src/commands/start.rs
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/src/bft.rs
  node/bft/src/gateway.rs
  node/bft/src/helpers/channels.rs
  node/bft/src/helpers/pending.rs
  node/bft/src/helpers/proposal.rs
  node/bft/src/helpers/signed_proposals.rs
  node/bft/src/helpers/storage.rs
  node/bft/src/primary.rs
  node/bft/src/sync/mod.rs
  node/bft/src/worker.rs
  node/bft/storage-service/Cargo.toml
  node/bft/storage-service/src/persistent.rs
  node/bft/tests/common/primary.rs
  node/bft/tests/components/pending.rs
  node/bft/tests/components/worker.rs
  node/bft/tests/narwhal_e2e.rs
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/rest/src/lib.rs
  node/rest/src/routes.rs
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/router/messages/src/helpers/node_type.rs
  node/router/src/handshake.rs
  node/src/client/router.rs
  node/src/validator/router.rs
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/sync/locators/src/block_locators.rs
  node/sync/src/block_sync.rs
  node/tcp/Cargo.toml
  rust-toolchain
  snarkos/main.rs
Labels: release, v3.4.0

#3471 [Feature] Batch proposal spend limits
  Cargo.lock
  Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/ledger-service/src/ledger.rs
  node/bft/ledger-service/src/mock.rs
  node/bft/ledger-service/src/prover.rs
  node/bft/ledger-service/src/traits.rs
  node/bft/ledger-service/src/translucent.rs
  node/bft/src/helpers/ready.rs
  node/bft/src/primary.rs
  node/bft/src/worker.rs
  node/rest/Cargo.toml
Labels: v3.5.0

#3513 [Fix] Proposal cache storage path configuration
  cli/src/commands/clean.rs
  node/bft/examples/simple_node.rs
  node/bft/src/bft.rs
  node/bft/src/helpers/proposal_cache.rs
  node/bft/src/primary.rs
  node/bft/src/sync/mod.rs
  node/bft/tests/common/primary.rs
  node/consensus/src/lib.rs
  node/tests/common/node.rs
Labels: v3.5.0

#3516 [Metrics] Introduce validator telemetry
  Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/src/bft.rs
  node/bft/src/gateway.rs
  node/bft/src/helpers/mod.rs
  node/bft/src/helpers/telemetry.rs
  node/bft/src/sync/mod.rs
  node/rest/Cargo.toml
  node/rest/src/lib.rs
  node/rest/src/routes.rs
Labels: v3.5.0

#3565 [Fix] Adjust proposal cache path when using custom storage paths
  node/bft/src/helpers/proposal_cache.rs
Labels: v3.5.0
