Repository ProvableHQ/snarkOS, pull requests merged in 2025-01, with the labels that each got.

#3464 Remove aleonet CI resource
  .circleci/config.yml
  README.md
Labels: 3.1.2

#3465 [Release] Mainnet v3.2.0
  .devnet/install.sh
  .devnet/reinstall.sh
  .github/ISSUE_TEMPLATE.md
  .integration/Cargo.toml
  .resources/release-version
  Cargo.lock
  Cargo.toml
  README.md
  account/Cargo.toml
  cli/Cargo.toml
  cli/src/helpers/updater.rs
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/storage-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/tcp/Cargo.toml
Labels: release, v3.2.0

#3466 Canary release v1.3.0
  Cargo.lock
  Cargo.toml
  node/rest/Cargo.toml
Labels: release, v1.3.0
