Repository ProvableHQ/snarkOS, pull requests merged in 2025-07, with the labels that each got.

#3694 [Optimize] Reduce Network Distribution of Invalid Solutions
  node/bft/ledger-service/src/ledger.rs
  node/rest/src/routes.rs
  node/src/client/mod.rs
Labels: v4.0.0

#3708 [Feat] Support Migration for Record Versioning Upgrade
  Cargo.lock
  Cargo.toml
  cli/src/commands/developer/decrypt.rs
  node/bft/events/src/disconnect.rs
  node/bft/src/primary.rs
  node/rest/src/lib.rs
  node/rest/src/routes.rs
Labels: v4.0.0

#3746 [Release] Mainnet 4.0.0
  .resources/release-version
  Cargo.lock
  Cargo.toml
  account/Cargo.toml
  cli/Cargo.toml
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/storage-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/tcp/Cargo.toml
Labels: release, v4.0.0

#3747 Minor feature flag fix for v4.0.1 release
  .resources/release-version
  Cargo.lock
  Cargo.toml
  account/Cargo.toml
  cli/Cargo.toml
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/storage-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/tcp/Cargo.toml
Labels: release, 4.0.1

#3638 [Feature] Program Upgradability.
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  cli/src/commands/developer/deploy.rs
  devnet.sh
  node/bft/ledger-service/src/ledger.rs
  node/bft/src/primary.rs
  node/bft/src/worker.rs
  node/rest/src/routes.rs
  node/router/messages/src/lib.rs
Labels: v4.1.0
