Repository ProvableHQ/snarkOS, pull requests merged in 2025-04, with the labels that each got.

#3576 [Release] Mainnet `v3.5.0`
  .integration/Cargo.toml
  .resources/release-version
  Cargo.lock
  Cargo.toml
  account/Cargo.toml
  cli/Cargo.toml
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/events/src/lib.rs
  node/bft/ledger-service/Cargo.toml
  node/bft/storage-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/tcp/Cargo.toml
Labels: release

#3568 [Docs] Add usage guide for validator telemetry
  README.md
  devnet.sh
  run-validator.sh
Labels: documentation, v3.7.0

#3589 chore: cargo update
  Cargo.lock
Labels: v3.7.0

#3608 Postrelease merge mainnet
  .circleci/config.yml
  .integration/Cargo.toml
  .integration/src/lib.rs
  .resources/release-version
  Cargo.lock
  Cargo.toml
  account/Cargo.toml
  cli/Cargo.toml
  display/Cargo.toml
  node/Cargo.toml
  node/bft/Cargo.toml
  node/bft/events/Cargo.toml
  node/bft/ledger-service/Cargo.toml
  node/bft/storage-service/Cargo.toml
  node/cdn/Cargo.toml
  node/consensus/Cargo.toml
  node/metrics/Cargo.toml
  node/rest/Cargo.toml
  node/router/Cargo.toml
  node/router/messages/Cargo.toml
  node/sync/Cargo.toml
  node/sync/communication-service/Cargo.toml
  node/sync/locators/Cargo.toml
  node/tcp/Cargo.toml
Labels: v3.7.0

#3596 [Feature] Introduce rolling Message versions
  Cargo.lock
  node/router/Cargo.toml
  node/router/messages/src/challenge_request.rs
  node/router/messages/src/lib.rs
  node/router/messages/src/ping.rs
  node/router/src/handshake.rs
  node/router/src/inbound.rs
  node/router/src/lib.rs
  node/router/tests/common/mod.rs
  node/router/tests/common/router.rs
  node/src/client/mod.rs
  node/src/client/router.rs
  node/src/prover/mod.rs
  node/src/prover/router.rs
  node/src/validator/mod.rs
  node/src/validator/router.rs
Labels: v3.7.0
